### ISSUE TITLE
Master should be main

### ISSUE THREAD

**Issue by DaveParr** [satRdays/satRday_site_template#19]
This is a known upcoming change to naming conventions on gitHub:
https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-

However, as we support the background to this change, there is no reason not to make the change now.

As well as changing the branch names in git, we will also have to consider the netlify deploy scripts, which may also be impacted.

**Comment by jdblischak** [comment]
It appears that the branch "main" has already been created and the branch "master" has already fallen behind. 

https://github.com/satRdays/satRday_site_template/branches

To avoid potential confusion, could the branch "master" be deleted and this issue closed?

**Comment by DaveParr** [comment]
Closed with commit: https://github.com/satRdays/satRday_site_template/commit/dd655817847e2d06f70ec55ecfa3c06ee8139a28
