### ISSUE TITLE
Remove triangle wave header

### ISSUE THREAD

**Issue by DaveParr** [satRdays/satRday_site_template#7]
long load time, people are turning it off specifically

**Comment by DaveParr** [comment]
Removed by @satRdays/berlin2019 
https://berlin2019.satrdays.org/

**Comment by amy17519** [comment]
If I am not wrong, this requires removing this line of html here https://github.com/satRdays/hugo-satrdays-theme/blob/6b6ec0eea4444dea29f03ce3fc2b6c06d056373f/layouts/partials/hero.html#L8

@DaveParr Can we make changes to the SatRday hugo template?

**Comment by stephlocke** [comment]
Yep! Ideally submit a PR :)
